#
spring-boot-grpc:

  env: default

  logRequests: true
  logResponses: true

  app:
    name: Spring-Boot-gRPC
    version: 1.0.0
    secret: asoifh98q34987658745q038dyhfjcas

grpc:
  port: 6565

ff4j:
  webapi:
    authentication: false
    authorization: false